pgo/api/urls.py
from django.urls import path

from pgo.api.routers import pgo_router
from pgo.api.views import BreakpointCalcAPIView, GoodToGoAPIView


pgo_api_urls = pgo_router.urls
pgo_api_urls.extend((
    path('breakpoint-calc/', BreakpointCalcAPIView.as_view(), name='breakpoint-calc'),
    path('good-to-go/', GoodToGoAPIView.as_view(), name='good-to-go'),
))

pgo/urls.py
from django.urls import path

from pgo.views import (
    BreakpointCalcRedirectView,
    BreakpointCalculatorView,
    GoodToGoView,
    MoveDetailView,
    MoveListView,
    PokemonDetailView,
    PokemonListView,
    FarewellView,
)

app_name = 'pgo'
urlpatterns = (
    path('pgo', BreakpointCalcRedirectView.as_view(), name='redirect'),
    path('breakpoint-calc/', BreakpointCalculatorView.as_view(), name='breakpoint-calc'),
    path('good-to-go/', GoodToGoView.as_view(), name='good-to-go'),

    path('pokemon/<slug:slug>', PokemonDetailView.as_view(), name='pokemon-detail'),
    path('pokemon/', PokemonListView.as_view(), name='pokemon-list'),
    path('moves/<slug:slug>', MoveDetailView.as_view(), name='move-detail'),
    path('moves/', MoveListView.as_view(), name='move-list'),

    path('farewell/', FarewellView.as_view(), name='farewell'),
    path('', BreakpointCalculatorView.as_view(), name='breakpoint-calc'),
)

pokestuff/urls.py
from django.conf import settings
from django.conf.urls import include
from django.urls import path
from django.conf.urls.static import static
from django.contrib import admin

from pgo.api.urls import pgo_api_urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-pgo/', include((pgo_api_urls, 'api-pgo'), namespace='api-pgo')),

    path('', include('pgo.urls', namespace='pgo')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
admin.site.enable_nav_sidebar = False

if settings.DEBUG_TOOLBAR:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

pgo/api/views.py
import six.moves.urllib as urllib
import copy
import logging

from collections import OrderedDict
from decimal import Decimal
from operator import itemgetter

from rest_framework import response, status, viewsets
from rest_framework.pagination import PageNumberPagination
from rest_framework.permissions import IsAuthenticatedOrReadOnly
from rest_framework.generics import GenericAPIView

from django.contrib.postgres.search import TrigramSimilarity
from django.urls import reverse
from django.shortcuts import get_object_or_404
from django.utils.text import slugify

from pgo.api.serializers import (
    BreakpointCalcSerializer, PokemonMoveSerializer, MoveSerializer,
    SimplePokemonSerializer, PokemonSerializer, TypeSerializer, GoodToGoSerializer,
)
from pgo.models import (
    CPM, PokemonMove, Move, Pokemon, Type, RaidBoss, RaidTier, WeatherCondition,
)
from pgo.utils import (
    calculate_damage_multiplier,
    calculate_dph,
    calculate_defender_health,
    calculate_cycle_dps,
    get_pokemon_data,
    get_move_data,
    get_top_counter_qs,
    determine_move_effectiveness,
    is_move_stab,
    MAX_IV,
)
logger = logging.getLogger(__name__)


class LargeResultsSetPagination(PageNumberPagination):
    page_size = 1000
    page_size_query_param = 'page_size'
    max_page_size = 2000


class LargeResultModelViewSet(viewsets.ModelViewSet):
    pagination_class = LargeResultsSetPagination


class MoveViewSet(LargeResultModelViewSet):
    permission_classes = (IsAuthenticatedOrReadOnly,)
    queryset = Move.objects.select_related('move_type')
    serializer_class = MoveSerializer

    def get_queryset(self):
        if 'pokemon-slug' in self.request.GET:
            self.serializer_class = PokemonMoveSerializer
            qs = PokemonMove.objects.filter(
                pokemon__slug=slugify(self.request.GET.get('pokemon-slug'))
            )

            if self.request.GET.get('exclude-legacy') == 'true':
                qs = qs.exclude(legacy=True)
            return qs
        else:
            return super().get_queryset()


class PokemonViewSet(viewsets.ModelViewSet):
    permission_classes = (IsAuthenticatedOrReadOnly,)
    queryset = Pokemon.objects.select_related('primary_type', 'secondary_type')
    serializer_class = PokemonSerializer

    def get_queryset(self):
        if 'raid-boss-tier-group' in self.request.GET:
            try:
                raid_tier_ids = RaidBoss.objects.filter(
                    raid_tier=self.request.GET.get('raid-boss-tier-group')
                ).values_list('pokemon__id', flat=True)

                return self.queryset.filter(
                    id__in=raid_tier_ids
                ).select_related(
                    'primary_type', 'secondary_type'
                ).order_by('name')
            except ValueError:
                pass

        return super().get_queryset()


class TypeViewSet(LargeResultModelViewSet):
    permission_classes = (IsAuthenticatedOrReadOnly,)
    queryset = Type.objects.all()
    serializer_class = TypeSerializer


class PokemonSimpleViewSet(LargeResultModelViewSet):
    permission_classes = (IsAuthenticatedOrReadOnly,)
    queryset = Pokemon.objects.select_related('primary_type', 'secondary_type')
    serializer_class = SimplePokemonSerializer
    lookup_field = 'slug'

    def get_queryset(self):
        pokemon_slug = slugify(self.request.GET.get('pokemon-slug', ''))

        if pokemon_slug:
            return self.queryset.annotate(
                similarity=TrigramSimilarity('slug', pokemon_slug)
            ).filter(
                similarity__gte=0.1
            ).order_by('-similarity')[:10]
        return super().get_queryset()


class BreakpointCalcAPIView(GenericAPIView):
    permission_classes = (IsAuthenticatedOrReadOnly,)
    serializer_class = BreakpointCalcSerializer

    def get(self, request, *args, **kwargs):
        self.current_tab = request.GET.get('tab', 'breakpoints')
        self.show_cinematic_breakpoints = request.GET.get('show_cinematic_breakpoints', False)
        self.top_counter_order = request.GET.get('top_counter_order', False)

        serializer = self.get_serializer(data=request.GET)
        serializer.is_valid(raise_exception=True)

        self._fetch_data(serializer.data)
        self._set_move_parameters()
        self._set_defender_health()
        self._set_move_stats(self.attacker.cpm_list.first()['value'], self.attacker.atk_iv)

        data = {
            'top_counters': self._get_top_counters_data(),
            'attack_iv_assessment': self._assess_attack_iv(),
            'breakpoint_details': self._get_details_table(self._process_data()),
        }
        return response.Response(data, status=status.HTTP_200_OK)

    def _fetch_data(self, data):
        cpm_qs = CPM.gyms.all()
        self.max_cpm_value = cpm_qs.filter(buddy_cpm=False).last().value

        attacker_slug = data.get('attacker')
        defender_slug = data.get('defender')
        if attacker_slug == defender_slug:
            pokemon = get_pokemon_data(attacker_slug)
            self.attacker = pokemon
            self.defender = copy.deepcopy(pokemon)
        else:
            self.attacker = get_pokemon_data(data.get('attacker'))
            self.defender = get_pokemon_data(data.get('defender'))

        self.attacker.atk_iv = data.get('attacker_atk_iv')
        self.attacker.level = data.get('attacker_level')
        self.attacker.cpm = cpm_qs.get(level=self.attacker.level)
        self.attacker.cpm_list = cpm_qs.filter(level__gte=self.attacker.level).values(
            'level', 'value', 'total_stardust_cost', 'total_candy_cost')

        self.defender.defense_iv = data.get('defense_iv', MAX_IV)
        self.defender.cpm = Decimal(data.get('defender_cpm')[:11])

        attacker_qk_move_id = data.get('attacker_quick_move')
        defender_qk_move_id = data.get('defender_quick_move')
        if attacker_qk_move_id == defender_qk_move_id:
            quick_move = get_move_data(attacker_qk_move_id)
            self.attacker_quick_move = quick_move
            self.defender.quick_move = copy.deepcopy(quick_move)
        else:
            self.attacker_quick_move = get_move_data(attacker_qk_move_id)
            self.defender.quick_move = get_move_data(defender_qk_move_id)

        attacker_cc_move_id = data.get('attacker_cinematic_move')
        defender_cc_move_id = data.get('defender_cinematic_move')
        if attacker_cc_move_id == defender_cc_move_id:
            cinematic_move = get_move_data(attacker_cc_move_id)
            self.attacker_cinematic_move = cinematic_move
            self.defender.cinematic_move = copy.deepcopy(cinematic_move)
        else:
            self.attacker_cinematic_move = get_move_data(attacker_cc_move_id)
            self.defender.cinematic_move = get_move_data(defender_cc_move_id)

        self.friendship_boost = data.get('friendship_boost', 1.00)
        self.raid_tier = None
        raid_tier = int(data.get('defender_cpm')[11:12])
        if raid_tier:
            self.raid_tier = RaidTier.objects.get(tier=raid_tier)

        self.boosted_types = []
        if data.get('weather_condition', 0) > 0:
            self.weather_condition = get_object_or_404(
                WeatherCondition.objects, pk=data.get('weather_condition'))
            self.boosted_types = list(
                self.weather_condition.types_boosted.values_list('pk', flat=True))

    def _process_data(self):
        attacker_starting_cpm = self.attacker.cpm_list.first()

        self._set_move_stats(attacker_cpm=attacker_starting_cpm['value'])
        starting_qk_dph = self.attacker_quick_move.damage_per_hit
        starting_cc_dph = self.attacker_cinematic_move.damage_per_hit

        self.perfect_max_dps = calculate_cycle_dps(
            self._get_max_damage_move(self.attacker_quick_move, attack_iv=MAX_IV),
            self._get_max_damage_move(self.attacker_cinematic_move, attack_iv=MAX_IV)
        )

        self.quick_move_proficiency = []
        self.cinematic_move_proficiency = []
        self.stardust_cost = attacker_starting_cpm['total_stardust_cost']
        self.candy_cost = attacker_starting_cpm['total_candy_cost']

        self._set_quick_move_proficiency(starting_qk_dph)
        self._set_cinematic_move_proficiency(
            starting_cc_dph,
            self._get_max_damage_move(self.attacker_cinematic_move).damage_per_hit
        )
        return starting_qk_dph

    def _set_move_parameters(self):
        self.attacker_quick_move.stab = is_move_stab(
            self.attacker_quick_move, self.attacker)
        self.attacker_cinematic_move.stab = is_move_stab(
            self.attacker_cinematic_move, self.attacker)

        self.attacker_quick_move.effectiveness = determine_move_effectiveness(
            self.attacker_quick_move.move_type, self.defender)
        self.attacker_cinematic_move.effectiveness = determine_move_effectiveness(
            self.attacker_cinematic_move.move_type, self.defender)

        self.attacker_quick_move.weather_boosted = \
            self.attacker_quick_move.move_type_id in self.boosted_types
        self.attacker_cinematic_move.weather_boosted = \
            self.attacker_cinematic_move.move_type_id in self.boosted_types

    def _set_defender_health(self):
        stamina = self.defender.pgo_stamina
        if self.raid_tier:
            self.defender.health = self.raid_tier.tier_stamina
        else:
            self.defender.health = calculate_defender_health(stamina + MAX_IV, self.defender.cpm)

    def _assess_attack_iv(self):
        buddy_max_cpm = self.attacker.cpm_list.last()['value']
        self._set_move_stats(attack_iv=self.attacker.atk_iv, attacker_cpm=buddy_max_cpm)
        buddy_current_qk_dph = self.attacker_quick_move.damage_per_hit
        self._set_move_stats(attack_iv=MAX_IV, attacker_cpm=buddy_max_cpm)
        buddy_max_qk_dph = self.attacker_quick_move.damage_per_hit

pgo/templates/pgo/farewell.html
{% extends 'pgo/move_list.html' %}

{% block title %}
  {{ block.super }} - Farewell
{% endblock title %}

{% block content %}
  <p>
    September 2020
  </p>
  <p>
    As many of you already know, I completely stopped playing PGo almost two years ago.
    Had a little comeback when PvP was released, but that didn't last and I've since moved
    on to other games, projects, and activities.
  </p>
  <p>
    Despite this I tried to keep the calculator updated for as long as possible, but
    recently other commercial and hobby projects have taken priority. The only time I had
    left to work on the breakpoint calc was time I'd rather spend with friends and family
    or sleeping.
  </p>
  <p>
    I never expected the breakpoint calc would live this long and for that I must thank
    all of you for using it and messaging me about game updates, but this is farewell. Maybe
    we'll meet again in some other game and then I might even be using your calculator :)
  </p>
{% endblock content %}

pgo/templates/pgo/good_to_go.html
{% extends 'pgo/pgo_base.html' %}
{% load render_bundle from webpack_loader %}

{% block title %}
  {{ block.super }} - Good to Go
{% endblock title %}

{% block meta_description %}
  <meta name="description" content="Good to Go is a comprehensive breakpoint calculator used to quickly figure out if your pokemon can hit the final quick move breakpoint for all selected matchups.">
{% endblock %}

{% block scripts %}
  {% render_bundle 'goodToGo' 'css' %}
{% endblock scripts %}

{% block content %}
  <div class="wrapper">
    <div class="input-wrapper">
      <div class="row">
        <div class="select-attacker-wrapper">
          <label for="choices-single-default" class="screen-reader">Select attacker</label>
          <select class="select-attacker" data-trigger name="choices-single-default" id="choices-single-default">
            <option value="-1" disabled selected>Select attacker</option>
          </select>
        </div>

        <div class="input-attacker-atk-iv-wrapper">
          <label for="select-atk-iv" class="screen-reader">Attacker ATK IV</label>
          <select id="select-atk-iv">
            <option value="-1" selected disabled>? ATK</option>
            {% for n in attack_iv_range %}
              <option value="{{ n }}">{{ n }} ATK</option>
            {% endfor %}
          </select>
        </div>
      </div>

      <div class="row">
        <div class="select-attacker-quick-move-wrapper">
          <label for="select-quick-move" class="screen-reader">Quick move</label>
          <select id="select-quick-move" disabled>
            <option value="-1" disabled selected>Quick move</option>
          </select>
        </div>

        <div class="select-weather-condition-wrapper">
          <label for="select-weather-condition" class="screen-reader">Weather condition</label>
          <select id="select-weather-condition">
            {% for weather_condition in weather_condition_data %}
              <option value="{{ weather_condition.pk }}">{{ weather_condition.name }}</option>
            {% endfor %}
          </select>
        </div>

        <input type="submit" class="toggle-buddy-boost" value="L41">
      </div>

      <div class="row">
        <div class="select-friendship-boost-wrapper">
          <label for="select-friendship-boost" class="screen-reader">Friendship boost</label>
          <select id="select-friendship-boost">
            {% for friend in friendship %}
              <option value="{{ friend.damage_boost }}">{{ friend.level }}</option>
            {% endfor %}
          </select>
        </div>
        <input type="submit" class="toggle-tier-3-5-raid-bosses pressed" value="T3-5 bosses">
        <input type="submit" class="toggle-tier-1-2-raid-bosses" value="T1-2 bosses">
      </div>
    </div>
    <div class="output-wrapper">
      <p>
        Good to Go is a comprehensive breakpoint calculator used to quickly figure out if your pokemon can hit the final quick move breakpoint for all selected matchups.
      </p>
      <p>
        Selecting an attacker and its ATK IV will auto submit the form. Changing any value will refresh the data.
      </p>
    </div>
  </div>
  <div class="results" hidden></div>
{% endblock content %}

{% block body_scripts %}
  {% render_bundle 'goodToGo' 'js' attrs='async' %}

  <script>
    var initialData = {{ initial_data|safe }};
    window.pgoAPIURLs = {
      'simple-pokemon-list': "{% url 'api-pgo:simple-pokemon-list' %}",
      'move-list': "{% url 'api-pgo:move-list' %}",
      'good-to-go': "{% url 'api-pgo:good-to-go' %}",
    };
  </script>
{% endblock body_scripts %}

pgo/templates/pgo/move_detail.html
{% extends 'pgo/move_list.html' %}
{% load pokestuff_tags %}

{% block title %}
  {{ block.super }} - {{ move.name }}
{% endblock title %}

{% block meta_description %}
  <meta name="description" content="The move detail page with stats.">
{% endblock %}

{% block content %}
  <div class="row">
    <table>
      <tr>
        <td colspan="2" class="list-search-wrapper cell-width-30">
          <label for="choices-single-default" class="screen-reader">
            Find move
          </label>
          <select class="list-search" data-trigger name="choices-single-default" id="choices-single-default">
            <option value="-1" disabled selected>
              Find move
            </option>
            {% for row in data %}
              <option value="{{ row.0 }}">
                {{ row.1 }}
              </option>
            {% endfor %}
          </select>
        </td>
        <td colspan="{% if preset == 'pve' %}6{% else %}5{% endif %}">
          <a href="?preset={% if preset == 'pve' %}pvp{% else %}pve{% endif %}">
            <span class="{% if preset == 'pvp' %}underline{% endif %}">
              PvP
            </span>
            /
            <span class="{% if preset == 'pve' %}underline{% endif %}">
              PvE
            </span>
          </a>
        </td>
      </tr>
      <tr>
        <th>
          Move
        </th>
        <th>
          PWR
        </th>
        <th>
          ENE
        </th>
        <th>
          <span class="cinematic-move-icon">&nbsp;</span>
        </th>
        {% if preset == 'pve' %}
          <th>
            DPS
          </th>
          <th>
            EPS
          </th>
        {% else %}
          <th>
            DPT
          </th>
          <th>
            EPT
          </th>
          <th>
            DPE
          </th>
        {% endif %}
      </tr>
      <tr>
        <td>
          <div class="move-wrapper">
            <a href="{% url 'pgo:move-detail' move.slug %}">
              <div>
                {{ move.name }}
              </div>
            </a>
            <div class="type-wrapper">
              <div class="type-{{ move.move_type.slug }}">
                {{ move.move_type.name }}
              </div>
            </div>
          </div>
        </td>
        {% if preset == 'pve' %}
          <td>{{ move.power }}</td>
          <td>{{ move.energy_delta }}</td>
          <td>{{ move.duration }}</td>
          <td>{{ move.dps }}</td>
          <td>{{ move.eps }}</td>
        {% else %}
          <td>{{ move.pvp_power }}</td>
          <td>{{ move.pvp_energy_delta }}</td>
          <td>{{ move.pvp_duration }}</td>
          <td>{{ move.dpt|default:"0" }}</td>
          <td>{{ move.ept|default:"0" }}</td>
          <td>{{ move.dpe|floatformat:"2"|default:"0" }}</td>
        {% endif %}
      </tr>
    </table>
  </div>
  <a class="list-link" href="{% url 'pgo:move-list' %}">
    Back to move list
  </a>
  <div class="pokemon-stats-table">
    <div class="row pokemon-resistance-weakness">
      <table>
        <tr>
          <th colspan="2">Super effective</th>
        </tr>
        {% for type, value in effectiveness_effective %}
          <tr>
            <td>
              <div class="type-{{ type|lower }}">
                {{ type }}
              </div>
            </td>
            <td>
              {% widthratio value 1 100 %}%
            </td>
          </tr>
        {% endfor %}
      </table>
      <table>
        <tr>
          <th colspan="2">Not very effective</th>
        </tr>
        {% for type, value in effectiveness_not_effective %}
          <tr>
            <td>
              <div class="type-{{ type|lower }}">
                {{ type }}
              </div>
            </td>
            <td>
              {% widthratio value 1 100 %}%
            </td>
          </tr>
        {% endfor %}
      </table>
    </div>
    <div class="row pokemon-stats-table">
      <table>
        <tr>
          <th>
            Who can learn {{ move.name }}?
          </th>
          <th>
            Atk
          </th>
          <th>
            Def
          </th>
          <th>
            Sta
          </th>
          <th>
            Prod
          </th>
          <th>
            CP
          </th>
        </tr>

        {% for pokemon_move in pokemon_moves %}
          {% with pokemon_move.pokemon as pokemon %}
            <tr>
              <td>
                <div class="pokemon-wrapper">
                  <a href="{% url 'pgo:pokemon-detail' pokemon.slug %}">
                    {{ pokemon.name }}
                  </a>
                  <div class="type-wrapper">
                    <div class="type-{{ pokemon.primary_type.slug }}">
                      {{ pokemon.primary_type.name }}
                    </div>
                    <div class="type-{{ pokemon.secondary_type.slug|default:"none" }}">
                      {{ pokemon.secondary_type.name|default:"" }}
                    </div>
                  </div>
                </div>
              </td>
              <td>{{ pokemon.pgo_attack }}</td>
              <td>{{ pokemon.pgo_defense }}</td>
              <td>{{ pokemon.pgo_stamina }}</td>
              <td>{{ pokemon.stat_product|format_stat_product }}</td>
              <td>{{ pokemon.maximum_cp|floatformat:"0" }}</td>
            </tr>
          {% endwith %}
        {% endfor %}
      </table>
    </div>
  </div>
{% endblock content %}

pgo/templates/pgo/pgo_base.html
{% extends 'pokestuff/base.html' %}
{% load pokestuff_tags %}

{% block title %}
  Pokemon GO
{% endblock title %}

{% block head %}
  {{ block.super }}

  {% block meta_description %}
    <meta name="description" content="Pokemon GO resources and tools.">
  {% endblock %}
  <meta name="keywords" content="breakpoint calculator, damage breakpoints, pokemon, pokemon go, pgo, game mechanics, game tools">
{% endblock head %}

{% block header %}
  {{ block.super }}
  {% navigation_tag %}
{% endblock header %}

{% block footer %}
  {% include 'pgo/includes/discontinued_message.html' %}
  {{ block.super }}
{% endblock footer %}

pgo/templates/pgo/pokemon_base.html
{% extends 'zenofewords/base.html' %}

pgo/templates/pgo/pokemon_detail.html
{% extends 'pgo/pokemon_list.html' %}
{% load pokestuff_tags %}

{% block title %}
  {{ block.super }} - {{ pokemon.name }}
{% endblock title %}

{% block meta_description %}
  <meta name="description" content="The Pokemon detail page with stats.">
{% endblock %}

{% block content %}
  <div class="row">
    <table>
      <tr>
        <td class="list-search-wrapper">
          <label for="pokemon-search" class="screen-reader">
            Find pokemon
          </label>
          <select class="list-search" data-trigger name="choices-single-default" id="pokemon-search">
            <option value="-1" disabled selected>
              Find pokemon
            </option>
          </select>
        </td>
        <th>
          Atk
        </th>
        <th>
          Def
        </th>
        <th>
          Sta
        </th>
        <th>
          Prod
        </th>
        <th>
          CP
        </th>
      </tr>
      <tr>
        <td>
          <div class="pokemon-wrapper">
            <a href="{% url 'pgo:pokemon-detail' pokemon.slug %}">
              {{ pokemon.name }}
            </a>
            <div class="type-wrapper">
              <div class="type-{{ pokemon.primary_type.slug }}">
                {{ pokemon.primary_type.name }}
              </div>
              <div class="type-{{ pokemon.secondary_type.slug }}">
                {{ pokemon.secondary_type.name|default:"" }}
              </div>
            </div>
          </div>
        </td>
        <td>{{ pokemon.pgo_attack }}</td>
        <td>{{ pokemon.pgo_defense }}</td>
        <td>{{ pokemon.pgo_stamina }}</td>
        <td>{{ pokemon.stat_product|format_stat_product }}</td>
        <td>{{ pokemon.maximum_cp|floatformat:"0" }}</td>
      </tr>
    </table>
  </div>
  <a class="list-link" href="{% url 'pgo:pokemon-list' %}">
    Back to pokemon list
  </a>
  <div class="row">
    <table class="move-stats-table">
      <tr>
        <th>
          Move stats
        </th>
        <td colspan="{% if preset == 'pve' %}5{% else %}6{% endif %}">
          <a href="?preset={% if preset == 'pve' %}pvp{% else %}pve{% endif %}">
            <span class="{% if preset == 'pvp' %}underline{% endif %}">
              PvP
            </span>
            /
            <span class="{% if preset == 'pve' %}underline{% endif %}">
              PvE
            </span>
          </a>
        </td>
      </tr>
      <tr>
        <th class="cell-width-30">
          Move
        </th>
        <th>
          PWR
        </th>
        <th>
          ENE
        </th>
        <th>
          <span class="cinematic-move-icon">&nbsp;</span>
        </th>
        {% if preset == 'pve' %}
          <th>
            DPS
          </th>
          <th>
            EPS
          </th>
        {% else %}
          <th>
            DPT
          </th>
          <th>
            EPT
          </th>
          <th>
            DPE
          </th>
        {% endif %}
      </tr>

      {% for pokemon_move in pokemon_moves %}
        {% with pokemon_move.move as move %}
          <tr>
            <td>
              <div class="pokemon-wrapper">
                <a href="{% url 'pgo:move-detail' move.slug %}">
                  <div>
                    {{ move.name }}
                    {% if pokemon_move.legacy %}
                      *
                    {% endif %}
                  </div>
                </a>
                <div class="type-wrapper">
                  <div class="type-{{ move.move_type.slug }}">
                    {{ move.move_type.name }}
                  </div>
                </div>
              </div>
            </td>
            {% if preset == 'pve' %}
              <td>{{ move.power }}</td>
              <td>{{ move.energy_delta }}</td>
              <td>{{ move.duration }}</td>
              <td>{{ move.dps }}</td>
              <td>{{ move.eps }}</td>
            {% else %}
              <td>{{ move.pvp_power }}</td>
              <td>{{ move.pvp_energy_delta }}</td>
              <td>{{ move.pvp_duration }}</td>
              <td>{{ move.dpt|default:"0" }}</td>
              <td>{{ move.ept|default:"0" }}</td>
              <td>{{ move.dpe|floatformat:"2"|default:"0" }}</td>
            {% endif %}
          </tr>
        {% endwith %}
      {% endfor %}
    </table>
  </div>
  <div class="pokemon-stats-table">
    <div class="row pokemon-resistance-weakness">
      <table>
        <tr>
          <th>
            Resistances
          </th>
          <th>
            &nbsp;
          </th>
        </tr>
        {% for resistance, value in pokemon.compound_resistance.items %}
          <tr>
            <td class="type-label-wrapper">
              <div class="type-{{ resistance|lower }}">
                {{ resistance }}
              </div>
            </td>
            <td>
              {% widthratio value 1 100 %}%
            </td>
          </tr>
        {% endfor %}
      </table>
      <table>
        <tr>
          <th>
            Weaknesses
          </th>
          <th>
            &nbsp;
          </th>
        </tr>
        {% for weakness, value in pokemon.compound_weakness.items %}
          <tr>
            <td class="type-label-wrapper">
              <div class="type-{{ weakness|lower }}">
                {{ weakness }}
              </div>
            </td>
            <td>
              {% widthratio value 1 100 %}%
            </td>
          </tr>
        {% endfor %}
      </table>
    </div>
    <div class="row pokemon-stats-table">
      <table>
        <tr>
          <th colspan="4">
            Perfect stats
          </th>
          <th>
            &nbsp;
          </th>
        </tr>
        <tr>
          <th>Level</th>
          <th>Attack</th>
          <th>Defense</th>
          <th>Stamina</th>
          <th>CP</th>
        </tr>
        {% for stats in pokemon_stats %}
          <tr>
            {% for value in stats %}
              <td>
                {{ value }}
              </td>
            {% endfor %}
          </tr>
        {% endfor %}
      </table>
    </div>
  </div>
{% endblock content %}